[package]
name = "pokedb"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
polars = "0.43.1"
postgres = { version = "0.19.8", features = ["with-serde_json-1"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
